### ISSUE TITLE
Indent if blocks differently?

### ISSUE THREAD

**Issue by cwebber** [hylang/hy-mode#29]
Some lisp modes (like emacs lisp... maybe only emacs lisp?) do if block indenting like this:

``` lisp
(if (foo-is-true)
    (do-this)
  (else-do-that))
```

Which makes it easier to tell which is the if-true, which is the if-false parts of the expression.  Noticing that the indentation is different helps me remember to wrap things in a (progn)!  I forget this in Hy a lot.

I'm not totally sure if this is the best way; I notice that scheme and common lisp by default show up like how hy-mode currently does it where they receive the same indentation level.  Thoughts?

**Comment by mhavard999** [comment]
I don't have an opinion either way, but clojure-mode also does not have this special indentation.

Anyway, on the hy doc site, it says to default to clojure with tricky language decisions.  idk if that same philosophy extends to here.

**Comment by gilch** [comment]
Old issue. And it's in the wrong place. I think we should decide things like this for Hy's style guide first, and *then* put it in the tools, so hy-mode and vim-hy don't have differing opinions.

Also, Hy's `if` is variadic now, like Python's if/elif/else, so that might change things.

I'm closing this until the style guide changes. @cwebber, if you're still interested, open a style guide issue on hylang/hy instead.
