### ISSUE TITLE
Syntax highlighting updates

### ISSUE THREAD

**Issue by ekaschalk** [hylang/hy-mode#45]
Are there any updates to syntax highlighting anyone wants?

For example, I personally highlight the symbol after the with-decorator tag macro. I also highlight tag macros themselves.

@gilch @Kodiologist

**Comment by gilch** [comment]
I'm not sure what I want. I want consistency, at least. We should look at how other Lisps do it. 

It would be nice if highlighting could distinguish a special form symbol from an ordinary function. This only seems to work partially at the moment. But highlight only when it's the head of a list, I guess, because elsewhere it it would typically refer to the shadowed version. But the core macros could have their own highlighting rules. For example a special form after the first argument at the top level of a `->` should probably be highlighted too, because it's acting as a special form there.

The built in macros are one thing, but figuring out what user macros mean for highlighting purposes is probably too hard for now. Eventually, maybe something could be specified with metadata. Start with simple, consistent rules for highlighting user macros.

"Reader syntax" like tag macros, the quoting prefixes ```~ ~@ ` '```, and non-symbol literals, like numbers, could have their own highlighting too. Some of this is already implemented, but I'm not sure if it's kept up with changes.

**Comment by Kodiologist** [comment]
The first thing to do is just to update the lists of keywords to highlight. For example, `let`, `nil`, and `nil?` no longer have any special meaning to Hy, whereas `xor` is now a builtin.

**Comment by ekaschalk** [comment]
I believe all keywords are synced now. Do you want hy internals like HySymbol highlighted?

**Comment by Kodiologist** [comment]
I could see that going either way. Right now the Hy model classes are sort-of-but-not-quite builtins. It's pretty dumb. On hylang/hy#1045, there was general acceptance of automatically importing them just like core functions, so that could happen in the future.

**Comment by ekaschalk** [comment]
I've finished and released the syntax highlighting updates I had planned, let me know if any additions or changes you guys want.
