### ISSUE TITLE
Hy file problems

### ISSUE THREAD

**Issue by teymuri** [hylang/hy-mode#78]
There are two problems currently for me using hy-mode on a debian and emacs 25+:

1. trying to open a file with .hy extension and hitting enter for the first time just does nothing, bringing emacs into some kind of infinit loop with over 100% CPU usage, i should cancel the opening with `C-g` and open it for the second time to get into the file without problem!

2. None of other modes i use with other lisps work in hy-mode (paredit, rainbowdelimiters)

**Comment by brandonwillard** [comment]
> 1. trying to open a file with .hy extension and hitting enter for the first time just does nothing, bringing emacs into some kind of infinit loop with over 100% CPU usage, i should cancel the opening with `C-g` and open it for the second time to get into the file without problem!

Can you post a link to the file you're attempting to open and tell us which version of `hy-mode` you're running?  You can copy the code here if it's small; otherwise, please use something like [pastebin](https://pastebin.com/).


> 2. None of other modes i use with other lisps work in hy-mode (paredit, rainbowdelimiters)

Minor modes like `rainbow-delimiters` should work with `hy-mode`, so first confirm that they're being called after `hy-mode` has successfully loaded (e.g. you might need to add those minor modes to the `hy-mode-hook`).  If `hy-mode` is fails to load correctly (as you describe above), then those hooks and subsequent minor modes might not load.

**Comment by ekaschalk** [comment]
Also please provide the version of Hy you are using.

For 1. see https://github.com/hylang/hy-mode/issues/61 which occurred for Hy 0.13 due to a dependency making breaking changes. I haven't heard the issue reproduced since then. The issue is occurring due to the internal hy process starting up for autocompletion/eldoc.

**Comment by teymuri** [comment]
Thanks for your reply! The file is empty, its just en empty file with .hy extension. The hy-mode version is 1.0.3. Can i give you more information?

**Comment by brandonwillard** [comment]
Yeah, I would guess that it's the internal Hy process, too.  If you search for a buffer with a name like "Hy Internal" (after canceling), you might be able to get more information.

**Comment by teymuri** [comment]
Ok, i reinstalled Hy and the above problems are solved. Thanks for your help!

**Comment by ekaschalk** [comment]
Great to hear and always feel free to reach out if you encounter problems or questions about hy-mode.
